# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm i -g yarn
  displayName: 'Install Yarn'

- script: |
    yarn install
  displayName: 'Install packages'

- script: |
    yarn test
  displayName: 'Test code'

- task: PublishTestResults@2
  displayName: 'Publish Test Restuls junit.xml'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: junit.xml

- script: |
    rm -rf node_modules
  displayName: 'Revmove packages'

- script: |
    yarn install --production --frozen-lockfile
    yarn build
  displayName: 'yarn install and build'
