apiVersion : apps/v1
kind: Deployment
metadata:
  name: heliosproof 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heliosproof
  template:
    metadata:
      labels:
        app: heliosproof 
    spec:
      containers:
        - name: heliosproof 
          image: rivethead42acr.azurecr.io/heliosproof
          ports:
          - containerPort: 3000